#ifndef DEMON_H
#define DEMON_H

namespace Progs {

void custom_demon_create(float points, float type);
void custom_demon_precache();
void custom_grunt_die();
void custom_shambler_die();
void sham_stand1();
void sham_walk1();
void sham_run1();
void sham_melee();
void sham_magic1();
void sham_pain(entity attacker, float damage);
float CheckArea(entity obj, entity builder);
void teamprefixsprint(float tno, entity ignore);
void MonsterTouch();
void ThrowMonsterHead(const string& gibname, float dm);
void ResetSlotPointer(entity player, float slot);
void Demon_Water_Jump();
void Demon_JumpTouch();
void demon1_stand1();
void demon1_stand2();
void demon1_stand3();
void demon1_stand4();
void demon1_stand5();
void demon1_stand6();
void demon1_stand7();
void demon1_stand8();
void demon1_stand9();
void demon1_stand10();
void demon1_stand11();
void demon1_stand12();
void demon1_stand13();
void demon1_walk1();
void demon1_walk2();
void demon1_walk3();
void demon1_walk4();
void demon1_walk5();
void demon1_walk6();
void demon1_walk7();
void demon1_walk8();
void demon1_run1();
void demon1_run2();
void demon1_run3();
void demon1_run4();
void demon1_run5();
void demon1_run6();
void demon1_jump1();
void demon1_jump2();
void demon1_jump3();
void demon1_jump4();
void demon1_jump5();
void demon1_jump6();
void demon1_jump7();
void demon1_jump8();
void demon1_jump9();
void demon1_jump10();
void demon1_jump13();
void demon1_jump11();
void demon1_jump12();
void demon1_atta1();
void demon1_atta2();
void demon1_atta3();
void demon1_atta4();
void demon1_atta5();
void demon1_atta6();
void demon1_atta7();
void demon1_atta8();
void demon1_atta9();
void demon1_atta10();
void demon1_atta11();
void demon1_atta12();
void demon1_atta13();
void demon1_atta14();
void demon1_atta15();
void demon1_pain1();
void demon1_pain2();
void demon1_pain3();
void demon1_pain4();
void demon1_pain5();
void demon1_pain6();
void demon1_fire1();
void Demon_Shoot_Fire(float side);
void demon1_fire1();
void demon1_fire2();
void demon1_fire3();
void demon1_fire4();
void demon1_fire5();
void demon1_fire6();
void demon1_fire7();
void demon1_fire8();
void demon1_fire9();
void demon1_fire10();
void demon1_fire11();
void demon1_fire12();
void demon1_fire13();
void demon1_fire14();
void demon1_fire15();
void demon1_pain(entity attacker, float damage);
void demon1_die1();
void demon1_die2();
void demon1_die3();
void demon1_die4();
void demon1_die5();
void demon1_die6();
void demon1_die7();
void demon1_die8();
void demon1_die9();
void Demon_MeleeAttack();
float CheckDemonMelee();
float CheckDemonFireBall(float inp);
float CheckDemonJump();
float DemonCheckAttack();
void Demon_Melee(float side);
void demon_fire_touch();
void Demon_Shoot_Fire(float side);
void demon_fire_touch();
void Demon_Water_Jump();
void Demon_JumpTouch();
void custom_demon_die();

} // END namespace Progs

#endif // END DEMON_H

