#define PR_AI_TELELINK_1                        1
#define PR_AI_TELELINK_2                        2
#define PR_AI_TELELINK_3                        4
#define PR_AI_TELELINK_4                        8
#define PR_AI_DOORFLAG                          16
#define PR_AI_PRECISION                         32
#define PR_AI_SURFACE                           64
#define PR_AI_BLIND                             128
#define PR_AI_JUMP                              256
#define PR_AI_DIRECTIONAL                       512
#define PR_AI_PLAT_BOTTOM                       1024
#define PR_AI_RIDE_TRAIN                        2048
#define PR_AI_SUPER_JUMP                        4096
#define PR_AI_SNIPER                            8192
#define PR_AI_AMBUSH                            16384
#define PR_AI_DOOR_NO_OPEN                      32768
#define PR_AI_DIFFICULT                         65536
#define PR_AI_TRACE_TEST                        131072
#define PR_AI_HANDLING_OBSTRUCTION              262144
#define PR_AI_HOLD_SELECT                       2
#define PR_AI_REJECT_TARGET                     524288
#define PR_AI_WAIT                              1048576
#define PR_AI_DANGER                            2097152
#define PR_AI_ON_REACHING_WAYPOINT              (1 | 2 | 4 | 8 | 32 | 64 | 128 | 256 | 1024 | 4096 | 8192 | 16384)
#define PR_AI_ON_PURSUING_WAYPOINT              (16 | 32 | 128 | 512 | 2048 | 32768)
#define PR_AI_IGNORE_TYPES                      (256 | 512 | 4096)

#define PR_PC_UNDEFINED                         0
#define PR_PC_SCOUT                             1
#define PR_PC_SNIPER                            2
#define PR_PC_SOLDIER                           3
#define PR_PC_DEMOMAN                           4
#define PR_PC_MEDIC                             5
#define PR_PC_HVYWEAP                           6
#define PR_PC_PYRO                              7
#define PR_PC_SPY                               8
#define PR_PC_ENGINEER                          9
#define PR_PC_RANDOM                            10
#define PR_PC_CUSTOM                            11
#define PR_PC_CIVILIAN                          12
#define PR_PC_LASTCLASS                         13

#define PR_WEAP_HOOK                            1
#define PR_WEAP_MEDIKIT                         4
#define PR_WEAP_SPANNER                         8
#define PR_WEAP_AXE                             16
#define PR_WEAP_SNIPER_RIFLE                    32
#define PR_WEAP_AUTO_RIFLE                      64
#define PR_WEAP_SHOTGUN                         128
#define PR_WEAP_SUPER_SHOTGUN                   256
#define PR_WEAP_NAILGUN                         512
#define PR_WEAP_LIGHT_ASSAULT                   1024
#define PR_WEAP_GRENADE_LAUNCHER                2048
#define PR_WEAP_FLAMETHROWER                    4096
#define PR_WEAP_ROCKET_LAUNCHER                 8192
#define PR_WEAP_INCENDIARY                      16384
#define PR_WEAP_ASSAULT_CANNON                  32768
#define PR_WEAP_LIGHTNING                       65536
#define PR_WEAP_DAEDALUS                        131072
#define PR_WEAP_TRANQ                           262144
#define PR_WEAP_RAILGUN                         524288
#define PR_WEAP_MAUSER                          1048576
#define PR_WEAP_AIRF                            2097152
#define PR_WEAP_LASERCANNON                     4194304
#define PR_WEAP_SNG                             8388608
#define PR_WEAP_ZEROGRAVITY                     16777216

#define PR_JOB_THIEF                            1
#define PR_JOB_RUNNER                           2
#define PR_JOB_WARLOCK                          4
#define PR_JOB_CHAPLAN                          8
#define PR_JOB_BERSERKER                        16
#define PR_JOB_GUERILLA                         32
#define PR_JOB_JUDOKA                           64
#define PR_JOB_ARMY                             128
#define PR_JOB_HACKER                           256
#define PR_JOB_MARTYR                           512
#define PR_JOB_CRUSADER                         1024
#define PR_JOB_ALL                              2047
#define PR_JOB_ACTIVE                           2048
#define PR_JOB_FULL_HIDE                        4096
#define PR_JOB_TIRED                            8192
#define PR_JOB_BLOODY_KNIFE                     16384
#define PR_JOB_EXTRA1                           65536
#define PR_JOB_EXTRA2                           131072

#define PR_NIT_SCANNER                          1
#define PR_NIT_TURRET                           2
#define PR_NIT_KEVLAR                           4
#define PR_NIT_GEL                              8
#define PR_NIT_BLAST                            16
#define PR_NIT_CERAMIC                          32
#define PR_NIT_ASBESTOS                         64
#define PR_NIT_AMMO_BACKPACK                    128
#define PR_NIT_AMMO_BANDOLIER                   256
#define PR_NIT_SCUBA                            512
#define PR_NIT_TESLA_CLOAKING                   512
#define PR_NIT_AUTOID                           1024
#define PR_NIT_AUTOMEDIC                        2048
#define PR_NIT_RESPAWN_GUARD                    4096
#define PR_NIT_AUTOSCANNER                      8192
#define PR_NIT_HOVER_BOOTS                      16384
#define PR_NIT_TESLA                            32768
#define PR_NIT_SECURITY_CAMERA                  65536
#define PR_NIT_TELEPORTER                       131072
#define PR_NIT_TESLA_UPGRADE                    262144
#define PR_NIT_HOVER_BOOTS_UPGRADE              524288
#define PR_NIT_RL_LASER_SIGHT                   1048576
#define PR_NIT_CLUSTER_ROCKETS                  2097152
#define PR_NIT_DOUBLETESLA                      4194304

#define PR_CUTF_DETPACK                         1
#define PR_CUTF_KNIFE                           2
#define PR_CUTF_SPY_KIT                         4
#define PR_CUTF_ASPECT_OF_HWGUY                 8
#define PR_CUTF_SENTRYGUN                       16
#define PR_CUTF_JAMMER                          32
#define PR_CUTF_FULLARMOUR                      64
#define PR_CUTF_CYBERAUG                        128
#define PR_CUTF_SENSOR                          256
#define PR_CUTF_TOSSABLEDET                     512
#define PR_CUTF_DISPENSER                       1024
#define PR_CUTF_STEALTH                         2048
#define PR_CUTF_HIGHJUMP                        4096
#define PR_CUTF_GYMNAST                         8192
#define PR_CUTF_DEMONLORE                       16384
#define PR_CUTF_EXPBODY                         32768
#define PR_CUTF_CLOSECOMBAT                     65536
#define PR_CUTF_HOLO                            131072
#define PR_CUTF_CLIPEXTEND                      262144
#define PR_CUTF_FIELDGEN                        524288
#define PR_CUTF_AIRFISTUPGRADE                  1048576
#define PR_CUTF_OTR                             2097152
#define PR_CUTF_DOUBLESENTRY                    4194304
