// PZ: THIS FILE IS NO LONGER NEEDED, SINCE MOVING TO A PROPER C++ BUILD -- AWAY FROM THE UNITY BUILD.

// PZ: Stick whatever prototypes you want in here (functions and variables); this file is compiled very early.
// Would be nice if we could just make the compiler (and precompiler, for that matter) perform two passes, first
// to just gather all symbol names. I hate having to do forward declarations -- one of the few things I hate about
// low-level languages.

void AGR_think();
void AGR_initialize();
void AGR_startTimer();
void AGR_stopTimer();
void AGR_resetTimer();
void AGR_playTimerSounds();
void AGR_introducePlayer();
void AGR_invPrint();
void AGR_precacheSounds();

void Invade_initialize();
void Invade_think();
void Invade_introducePlayer();
void Invade_invPrint();
void Invade_startPrematch();
float Invade_buffPlayer(entity player);
void Invade_playTimerSounds();
void Invade_precacheSounds();

void ExtendedCPrint(entity tgt, const string& str, float iterations, float delayBtwPrints, float flash);
void ExtendedCPrintThink();
entity Finditem(float ino);

void armor_touch();

float modelindex_eyes, modelindex_player, modelindex_null; // want these accessible everywhere

// LinkedList module (bot_misc.qc)
entity LinkedList_addNodeToEndOf(entity firstNode, const string& LinkedList_description);
entity LinkedList_removeNode(entity firstNode, entity nodeToRemove);
void LinkedList_deleteList(entity firstNode);
entity LinkedList_swapNodes(entity firstNode, entity e1, entity e2);

void frik_updateWaypointEditorForSelf();
void frik_createWaypointVisualMarker(entity waypoint);
void timerThink_botEnsureWeaponSelection();

FIELD(".entity npc_nextTeamList;")
FIELD(".entity npc_nextEntInTeamList;")

entity frik_findNearestEntityToSelfWithThisClassname(const string& s);
void s_explode1();
void frik_checkForStuckBot();
void frik_updateWaypointLinkPointers(entity waypoint);
void frik_updateWaypointLinkNumbers(entity waypoint);
void timerCleanup_botEnsureWeaponSelection();
entity frik_getGoalTarget();
void frik_botSayDebug(const string& h);

//float areFamilyMembers(entity a, entity b);  // PZ NOTE: This should probably only be used by Teammate().
float GetCurrentLegs();
float GetPreviousLegs();
float GetCurrentHPItem();
float modulo(float a, float b);
//float Teammate(float targteam, float attackteam);
float roundFloat(float x);
void AddAura(float aur);
void CrusaderAddInvisibility();
void handleCrusader();
void TeamFortress_SpyChangeSkin(float playerClass);  // PZ: renamed from "class" for C++
void TeamFortress_SpyChangeColor(float teamno);
void handleSpy();
void handleJudo();
void timerThink_botFinishTypingMsg();
float crandom();
void Attack_Finished(float att_delay);
void handleThief();
void isBotInEnemyFieldOfView();
void handleHacker();
float botAttemptHacking(entity e, float isEnemy);
void InitiateInterface(float input);
void frik_updateWaypointVisualMarkers();
void Menu_VoteBot();
void Player_VoteBot();
void Menu_VoteBot_Input(float input);
// PZ: BEGIN - Stupid forward declarations for frame functions.
//     I used the following command to quickly grab these from the files:  grep -io 'void[ \t]*[_a-z0-9]*[0-9]()' FILENAME.cpp | sed 's/()/();/g'
void s_explode2(); void s_explode3(); void s_explode4(); void s_explode5(); void s_explode6();
void player_shot2(); void player_shot3(); void player_shot4(); void player_shot5(); void player_shot6();
void player_autorifle2(); void player_autorifle3();
void player_axe2(); void player_axe3(); void player_axe4();
void player_axeb2(); void player_axeb3(); void player_axeb4();
void player_axec2(); void player_axec3(); void player_axec4();
void player_axed2(); void player_axed3(); void player_axed4();
void player_chain1a(); void player_chain2a();
void player_medikit2(); void player_medikit3(); void player_medikit4();
void player_medikitb2(); void player_medikitb3(); void player_medikitb4();
void player_medikitc2(); void player_medikitc3(); void player_medikitc4();
void player_medikitd2(); void player_medikitd3(); void player_medikitd4();
void player_bioweapon2(); void player_bioweapon3(); void player_bioweapon4();
void player_bioweaponb2(); void player_bioweaponb3(); void player_bioweaponb4();
void player_bioweaponc2(); void player_bioweaponc3(); void player_bioweaponc4();
void player_bioweapond2(); void player_bioweapond3(); void player_bioweapond4();
void player_snail2(); void player_nail2(); void player_nail3(); void player_nail4();
void player_assaultcannonup2(); void player_assaultcannon2();
void player_light2(); void player_light_assault2();
void player_rocket2(); void player_rocket3(); void player_rocket4(); void player_rocket5(); void player_rocket6();
void player_pain2(); void player_pain3(); void player_pain4(); void player_pain5(); void player_pain6();
void player_axpain2(); void player_axpain3(); void player_axpain4(); void player_axpain5(); void player_axpain6();
void player_diea2(); void player_diea3(); void player_diea4(); void player_diea5(); void player_diea6(); void player_diea7(); void player_diea8(); void player_diea9(); void player_diea10(); void player_diea11();
void player_dieb2(); void player_dieb3(); void player_dieb4(); void player_dieb5(); void player_dieb6(); void player_dieb7(); void player_dieb8(); void player_dieb9();
void player_diec2(); void player_diec3(); void player_diec4(); void player_diec5(); void player_diec6(); void player_diec7(); void player_diec8(); void player_diec9(); void player_diec10(); void player_diec11(); void player_diec12(); void player_diec13(); void player_diec14(); void player_diec15();
void player_died2(); void player_died3(); void player_died4(); void player_died5(); void player_died6(); void player_died7(); void player_died8(); void player_died9();
void player_diee2(); void player_diee3(); void player_diee4(); void player_diee5(); void player_diee6(); void player_diee7(); void player_diee8(); void player_diee9();
void player_die_ax2(); void player_die_ax3(); void player_die_ax4(); void player_die_ax5(); void player_die_ax6(); void player_die_ax7(); void player_die_ax8(); void player_die_ax9();
void player_diee2(); void player_diee3(); void player_diee4(); void player_diee5(); void player_diee6(); void player_diee7(); void player_diee8(); void player_diee9();
void player_airgun2(); void player_airgun3(); void player_airgun4(); void player_airgun5(); void player_airgun6(); void player_airgun7(); void player_airgun8();
void player_failedairgun2(); void player_failedairgun3();
void player_laser2(); void player_laser3(); void player_laser4();
void lvl2_sentry_atk2(); void lvl3_sentry_atk2(); void lvl3_sentry_atk5();
void tsla_on2(); void tsla_on3(); void tsla_on4(); void tsla_on5(); void tsla_on6(); void tsla_on7(); void tsla_on8(); void tsla_on9(); void tsla_on10(); void tsla_on11(); void tsla_on12(); void tsla_on13(); void tsla_on14();
void tsla_fire2(); void tsla_fire3(); void tsla_fire4(); void tsla_fire5(); void tsla_fire6(); void tsla_fire7(); void tsla_fire8(); void tsla_fire9(); void tsla_fire10(); void tsla_fire11(); void tsla_fire12();
void demon1_stand2();void demon1_stand3();void demon1_stand4();void demon1_stand5();void demon1_stand6();void demon1_stand7();void demon1_stand8();void demon1_stand9();void demon1_stand10();void demon1_stand11();void demon1_stand12();void demon1_stand13();
void demon1_walk2();void demon1_walk3();void demon1_walk4();void demon1_walk5();void demon1_walk6();void demon1_walk7();void demon1_walk8();
void demon1_run2();void demon1_run3();void demon1_run4();void demon1_run5();void demon1_run6();
void demon1_jump2();void demon1_jump3();void demon1_jump4();void demon1_jump5();void demon1_jump6();void demon1_jump7();void demon1_jump8();void demon1_jump9();void demon1_jump10();void demon1_jump13();void demon1_jump11();void demon1_jump12();
void demon1_atta2();void demon1_atta3();void demon1_atta4();void demon1_atta5();void demon1_atta6();void demon1_atta7();void demon1_atta8();void demon1_atta9();void demon1_atta10();void demon1_atta11();void demon1_atta12();void demon1_atta13();void demon1_atta14();void demon1_atta15();
void demon1_pain2();void demon1_pain3();void demon1_pain4();void demon1_pain5();void demon1_pain6();
void demon1_fire2();void demon1_fire3();void demon1_fire4();void demon1_fire5();void demon1_fire6();void demon1_fire7();void demon1_fire8();void demon1_fire9();void demon1_fire10();void demon1_fire11();void demon1_fire12();void demon1_fire13();void demon1_fire14();void demon1_fire15();
void demon1_die2();void demon1_die3();void demon1_die4();void demon1_die5();void demon1_die6();void demon1_die7();void demon1_die8();void demon1_die9();
void sham_stand2();void sham_stand3();void sham_stand4();void sham_stand5();void sham_stand6();void sham_stand7();void sham_stand8();void sham_stand9();void sham_stand10();void sham_stand11();void sham_stand12();void sham_stand13();void sham_stand14();void sham_stand15();void sham_stand16();void sham_stand17();void sham_walk1();
void sham_walk2();void sham_walk3();void sham_walk4();void sham_walk5();void sham_walk6();void sham_walk7();void sham_walk8();void sham_walk9();void sham_walk10();void sham_walk11();void sham_walk12();
void sham_run2();void sham_run3();void sham_run4();void sham_run5();void sham_run6();
void sham_smash2();void sham_smash3();void sham_smash4();void sham_smash5();void sham_smash6();void sham_smash7();void sham_smash8();void sham_smash9();void sham_smash10();void sham_smash11();void sham_smash12();
void sham_swingl2();void sham_swingl3();void sham_swingl4();void sham_swingl5();void sham_swingl6();void sham_swingl7();void sham_swingl8();void sham_swingl9();
void sham_swingr2();void sham_swingr3();void sham_swingr4();void sham_swingr5();void sham_swingr6();void sham_swingr7();void sham_swingr8();void sham_swingr9();
void sham_magic2();void sham_magic3();void sham_magic4();void sham_magic5();void sham_magic6();void sham_magic9();void sham_magic10();void sham_magic11();void sham_magic12();
void sham_pain2();void sham_pain3();void sham_pain4();void sham_pain5();void sham_pain6();
void sham_death2();void sham_death3();void sham_death4();void sham_death5();void sham_death6();void sham_death7();void sham_death8();void sham_death9();void sham_death10();void sham_death11();
void sham_xmas2();void sham_xmas3();void sham_xmas4();void sham_xmas5();void sham_xmas6();void sham_xmas7();void sham_xmas8();void sham_xmas9();void sham_xmas10();void sham_xmas11();void sham_xmas12();void sham_xmas13();void sham_xmas14();void sham_xmas15();void sham_xmas16();void sham_xmas17();void sham_xmas18();void sham_xmas19();void sham_xmas20();void sham_xmas21();void sham_xmas22();void sham_xmas23();void sham_xmas24();void sham_xmas25();void sham_xmas26();void sham_xmas27();void sham_xmas28();void sham_xmas29();void sham_xmas30();void sham_xmas31();void sham_xmas32();void sham_xmas33();
void grunty_nail2();void grunty_nail3();void grunty_nail4();
void grunty_diea2();void grunty_diea3();void grunty_diea4();void grunty_diea5();void grunty_diea6();void grunty_diea7();void grunty_diea8();void grunty_diea9();void grunty_diea10();void grunty_diea11();
void grunty_dieb2();void grunty_dieb3();void grunty_dieb4();void grunty_dieb5();void grunty_dieb6();void grunty_dieb7();void grunty_dieb8();void grunty_dieb9();
void grunty_diec2();void grunty_diec3();void grunty_diec4();void grunty_diec5();void grunty_diec6();void grunty_diec7();void grunty_diec8();void grunty_diec9();void grunty_diec10();void grunty_diec11();void grunty_diec12();void grunty_diec13();void grunty_diec14();void grunty_diec15();
void grunty_died2();void grunty_died3();void grunty_died4();void grunty_died5();void grunty_died6();void grunty_died7();void grunty_died8();void grunty_died9();
void grunty_diee2();void grunty_diee3();void grunty_diee4();void grunty_diee5();void grunty_diee6();void grunty_diee7();void grunty_diee8();void grunty_diee9();
void grunty_die_ax2();void grunty_die_ax3();void grunty_die_ax4();void grunty_die_ax5();void grunty_die_ax6();void grunty_die_ax7();void grunty_die_ax8();void grunty_die_ax9();
void grunty_pain2();void grunty_pain3();void grunty_pain4();void grunty_pain5();void grunty_pain6();
void grunty_axepain2();void grunty_axepain3();void grunty_axepain4();void grunty_axepain5();void grunty_axepain6();
void wiz_stand2();void wiz_stand3();void wiz_stand4();void wiz_stand5();void wiz_stand6();void wiz_stand7();void wiz_stand8();
void wiz_walk2();void wiz_walk3();void wiz_walk4();void wiz_walk5();void wiz_walk6();void wiz_walk7();void wiz_walk8();
void wiz_side2();void wiz_side3();void wiz_side4();void wiz_side5();void wiz_side6();void wiz_side7();void wiz_side8();
void wiz_run2();void wiz_run3();void wiz_run4();void wiz_run5();void wiz_run6();void wiz_run7();void wiz_run8();void wiz_run9();void wiz_run10();void wiz_run11();void wiz_run12();void wiz_run13();void wiz_run14();
void wiz_fast2();void wiz_fast3();void wiz_fast4();void wiz_fast5();void wiz_fast6();void wiz_fast7();void wiz_fast8();void wiz_fast9();void wiz_fast10();
void wiz_pain2();void wiz_pain3();void wiz_pain4();
void wiz_death2();void wiz_death3();void wiz_death4();void wiz_death5();void wiz_death6();void wiz_death7();void wiz_death8();
void fish_stand2();void fish_stand3();void fish_stand4();void fish_stand5();void fish_stand6();void fish_stand7();void fish_stand8();void fish_stand9();void fish_stand10();void fish_stand11();void fish_stand12();void fish_stand13();void fish_stand14();void fish_stand15();void fish_stand16();void fish_stand17();void fish_stand18();
void fish_walk2();void fish_walk3();void fish_walk4();void fish_walk5();void fish_walk6();void fish_walk7();void fish_walk8();void fish_walk9();void fish_walk10();void fish_walk11();void fish_walk12();void fish_walk13();void fish_walk14();void fish_walk15();void fish_walk16();void fish_walk17();void fish_walk18();
void fish_run2();void fish_run3();void fish_run4();void fish_run5();void fish_run6();void fish_run7();void fish_run8();void fish_run9();
void fish_attack2();void fish_attack3();void fish_attack4();void fish_attack5();void fish_attack6();void fish_attack7();void fish_attack8();void fish_attack9();void fish_attack10();void fish_attack11();void fish_attack12();void fish_attack13();void fish_attack14();void fish_attack15();void fish_attack16();void fish_attack17();void fish_attack18();
void fish_death2();void fish_death3();void fish_death4();void fish_death5();void fish_death6();void fish_death7();void fish_death8();void fish_death9();void fish_death10();void fish_death11();void fish_death12();void fish_death13();void fish_death14();void fish_death15();void fish_death16();void fish_death17();void fish_death18();void fish_death19();void fish_death20();void fish_death21();
void fish_pain2();void fish_pain3();void fish_pain4();void fish_pain5();void fish_pain6();void fish_pain7();void fish_pain8();void fish_pain9();
void fish_toss2();void fish_toss3();void fish_toss4();void fish_toss5();void fish_toss6();void fish_toss7();void fish_toss8();void fish_toss9();void fish_toss10();void fish_toss11();void fish_toss12();void fish_toss13();void fish_toss14();void fish_toss15();void fish_toss16();void fish_toss17();void fish_toss18();
void gremlin_stand2();void gremlin_stand3();void gremlin_stand4();void gremlin_stand5();void gremlin_stand6();void gremlin_stand7();void gremlin_stand8();void gremlin_stand9();void gremlin_stand10();void gremlin_stand11();void gremlin_stand12();void gremlin_stand13();void gremlin_stand14();void gremlin_stand15();void gremlin_stand16();void gremlin_stand17();
void gremlin_walk2();void gremlin_walk3();void gremlin_walk4();void gremlin_walk5();void gremlin_walk6();void gremlin_walk7();void gremlin_walk8();void gremlin_walk9();void gremlin_walk10();void gremlin_walk11();void gremlin_walk12();
void gremlin_run2();void gremlin_run3();void gremlin_run4();void gremlin_run5();void gremlin_run6();void gremlin_run7();void gremlin_run8();void gremlin_run9();void gremlin_run10();void gremlin_run11();void gremlin_run12();void gremlin_run13();void gremlin_run14();void gremlin_run15();
void gremlin_jump2();void gremlin_jump3();void gremlin_jump4();void gremlin_jump5();void gremlin_jump6();void gremlin_jump7();void gremlin_jump8();void gremlin_jump9();void gremlin_jump10();void gremlin_jump11();void gremlin_jump12();void gremlin_jump13();void gremlin_jump14();void gremlin_jump15();void gremlin_jump16();
void gremlin_shot2();void gremlin_shot3();void gremlin_shot4();void gremlin_shot5();void gremlin_shot6();
void gremlin_nail2();void gremlin_nail3();void gremlin_nail4();void gremlin_nail5();void gremlin_nail6();void gremlin_nail7();
void gremlin_laser2();void gremlin_laser3();void gremlin_laser4();void gremlin_laser5();void gremlin_laser6();void gremlin_laser7();
void gremlin_light2();void gremlin_light3();void gremlin_light4();void gremlin_light5();
void gremlin_rocket2();void gremlin_rocket3();void gremlin_rocket4();void gremlin_rocket5();void gremlin_rocket6();
void gremlin_lunge2();void gremlin_lunge3();void gremlin_lunge4();void gremlin_lunge5();void gremlin_lunge6();void gremlin_lunge7();void gremlin_lunge8();void gremlin_lunge9();void gremlin_lunge10();void gremlin_lunge11();
void gremlin_claw2();void gremlin_claw3();void gremlin_claw4();void gremlin_claw5();void gremlin_claw6();void gremlin_claw7();void gremlin_claw8();void gremlin_claw9();void gremlin_claw10();void gremlin_claw11();
void gremlin_gorge2();void gremlin_gorge3();void gremlin_gorge4();void gremlin_gorge5();void gremlin_gorge6();void gremlin_gorge7();void gremlin_gorge8();void gremlin_gorge9();void gremlin_gorge10();void gremlin_gorge11();void gremlin_gorge12();void gremlin_gorge13();
void gremlin_look2();void gremlin_look3();void gremlin_look4();void gremlin_look5();void gremlin_look6();void gremlin_look7();void gremlin_look8();void gremlin_look9();
void gremlin_glook2();void gremlin_glook3();void gremlin_glook4();void gremlin_glook5();void gremlin_glook6();void gremlin_glook7();void gremlin_glook8();void gremlin_glook9();void gremlin_glook10();void gremlin_glook11();void gremlin_glook12();void gremlin_glook13();void gremlin_glook14();void gremlin_glook15();void gremlin_glook16();void gremlin_glook17();void gremlin_glook18();void gremlin_glook19();void gremlin_glook20();
void gremlin_pain2();void gremlin_pain3();void gremlin_pain4();
void gremlin_gunpain2();void gremlin_gunpain3();
void gremlin_spawn2();void gremlin_spawn3();void gremlin_spawn4();void gremlin_spawn5();void gremlin_spawn6();
void gremlin_die2();void gremlin_die3();void gremlin_die4();void gremlin_die5();void gremlin_die6();void gremlin_die7();void gremlin_die8();void gremlin_die9();void gremlin_die10();void gremlin_die11();void gremlin_die12();
void gremlin_flip2();void gremlin_flip3();void gremlin_flip4();void gremlin_flip5();void gremlin_flip6();void gremlin_flip7();void gremlin_flip8();
void gremlin_gstand2();void gremlin_gstand3();void gremlin_gstand4();void gremlin_gstand5();void gremlin_gstand6();void gremlin_gstand7();void gremlin_gstand8();void gremlin_gstand9();void gremlin_gstand10();void gremlin_gstand11();void gremlin_gstand12();void gremlin_gstand13();void gremlin_gstand14();void gremlin_gstand15();void gremlin_gstand16();void gremlin_gstand17();void gremlin_gstand18();void gremlin_gstand19();void gremlin_gstand20();
void gremlin_gwalk2();void gremlin_gwalk3();void gremlin_gwalk4();void gremlin_gwalk5();void gremlin_gwalk6();void gremlin_gwalk7();void gremlin_gwalk8();void gremlin_gwalk9();void gremlin_gwalk10();void gremlin_gwalk11();void gremlin_gwalk12();void gremlin_gwalk13();void gremlin_gwalk14();void gremlin_gwalk15();
void run_ablast2();void run_ablast3();void run_ablast4();void run_ablast5();void run_ablast6();
void run_ablastWater2();void run_ablastWater3();void run_ablastWater4();void run_ablastWater5();void run_ablastWater6();void run_ablastWater7();void run_ablastWater8();void run_ablastWater9();void run_ablastWater10();
void spy_diea2();void spy_diea3();void spy_diea4();void spy_diea5();void spy_diea6();void spy_diea7();void spy_diea8();void spy_diea9();void spy_diea10();void spy_diea11();
void spy_dieb2();void spy_dieb3();void spy_dieb4();void spy_dieb5();void spy_dieb6();void spy_dieb7();void spy_dieb8();void spy_dieb9();
void spy_diec2();void spy_diec3();void spy_diec4();void spy_diec5();void spy_diec6();void spy_diec7();void spy_diec8();void spy_diec9();void spy_diec10();void spy_diec11();void spy_diec12();void spy_diec13();void spy_diec14();void spy_diec15();
void spy_died2();void spy_died3();void spy_died4();void spy_died5();void spy_died6();void spy_died7();void spy_died8();void spy_died9();
void spy_diee2();void spy_diee3();void spy_diee4();void spy_diee5();void spy_diee6();void spy_diee7();void spy_diee8();void spy_diee9();
void spy_die_ax2();void spy_die_ax3();void spy_die_ax4();void spy_die_ax5();void spy_die_ax6();void spy_die_ax7();void spy_die_ax8();void spy_die_ax9();
void spy_upb2();void spy_upb3();void spy_upb4();void spy_upb5();void spy_upb6();void spy_upb7();void spy_upb8();void spy_upb9();
void spy_upc2();void spy_upc3();void spy_upc4();void spy_upc5();void spy_upc6();void spy_upc7();void spy_upc8();void spy_upc9();void spy_upc10();void spy_upc11();void spy_upc12();void spy_upc13();void spy_upc14();void spy_upc15();
void spy_upd2();void spy_upd3();void spy_upd4();void spy_upd5();void spy_upd6();void spy_upd7();void spy_upd8();void spy_upd9();
void spy_upe2();void spy_upe3();void spy_upe4();void spy_upe5();void spy_upe6();void spy_upe7();void spy_upe8();void spy_upe9();
void spy_upaxe2();void spy_upaxe3();void spy_upaxe4();void spy_upaxe5();void spy_upaxe6();void spy_upaxe7();void spy_upaxe8();void spy_upaxe9();
void ab_exp2();void ab_exp3();void ab_exp4();void ab_exp5();void ab_exp6();
#ifdef PR_COOP_MODE_ENHANCED
void army_stand2();void army_stand3();void army_stand4();void army_stand5();void army_stand6();void army_stand7();void army_stand8();
void army_walk2();void army_walk3();void army_walk4();void army_walk5();void army_walk6();void army_walk7();void army_walk8();void army_walk9();void army_walk10();void army_walk11();void army_walk12();void army_walk13();void army_walk14();void army_walk15();void army_walk16();void army_walk17();void army_walk18();void army_walk19();void army_walk20();void army_walk21();void army_walk22();void army_walk23();void army_walk24();
void army_run2();void army_run3();void army_run4();void army_run5();void army_run6();void army_run7();void army_run8();
void army_atk2();void army_atk3();void army_atk4();void army_atk5();void army_atk6();void army_atk7();void army_atk8();void army_atk9();
void army_pain2();void army_pain3();void army_pain4();void army_pain5();void army_pain6();
void army_painb2();void army_painb3();void army_painb4();void army_painb5();void army_painb6();void army_painb7();void army_painb8();void army_painb9();void army_painb10();void army_painb11();void army_painb12();void army_painb13();void army_painb14();
void army_painc2();void army_painc3();void army_painc4();void army_painc5();void army_painc6();void army_painc7();void army_painc8();void army_painc9();void army_painc10();void army_painc11();void army_painc12();void army_painc13();
void army_die2();void army_die3();void army_die4();void army_die5();void army_die6();void army_die7();void army_die8();void army_die9();void army_die10();
void army_cdie2();void army_cdie3();void army_cdie4();void army_cdie5();void army_cdie6();void army_cdie7();void army_cdie8();void army_cdie9();void army_cdie10();void army_cdie11();
void dog_stand2();void dog_stand3();void dog_stand4();void dog_stand5();void dog_stand6();void dog_stand7();void dog_stand8();void dog_stand9();
void dog_walk2();void dog_walk3();void dog_walk4();void dog_walk5();void dog_walk6();void dog_walk7();void dog_walk8();
void dog_run2();void dog_run3();void dog_run4();void dog_run5();void dog_run6();void dog_run7();void dog_run8();void dog_run9();void dog_run10();void dog_run11();void dog_run12();
void dog_atta2();void dog_atta3();void dog_atta4();void dog_atta5();void dog_atta6();void dog_atta7();void dog_atta8();
void dog_leap2();void dog_leap3();void dog_leap4();void dog_leap5();void dog_leap6();void dog_leap7();void dog_leap8();void dog_leap9();
void dog_pain2();void dog_pain3();void dog_pain4();void dog_pain5();void dog_pain6();
void dog_painb2();void dog_painb3();void dog_painb4();void dog_painb5();void dog_painb6();void dog_painb7();void dog_painb8();void dog_painb9();void dog_painb10();void dog_painb11();void dog_painb12();void dog_painb13();void dog_painb14();void dog_painb15();void dog_painb16();
void dog_die2();void dog_die3();void dog_die4();void dog_die5();void dog_die6();void dog_die7();void dog_die8();void dog_die9();
void dog_dieb2();void dog_dieb3();void dog_dieb4();void dog_dieb5();void dog_dieb6();void dog_dieb7();void dog_dieb8();void dog_dieb9();
void zombie_stand2();void zombie_stand3();void zombie_stand4();void zombie_stand5();void zombie_stand6();void zombie_stand7();void zombie_stand8();void zombie_stand9();void zombie_stand10();void zombie_stand11();void zombie_stand12();void zombie_stand13();void zombie_stand14();void zombie_stand15();
void zombie_cruc2();void zombie_cruc3();void zombie_cruc4();void zombie_cruc5();void zombie_cruc6();
void zombie_walk2();void zombie_walk3();void zombie_walk4();void zombie_walk5();void zombie_walk6();void zombie_walk7();void zombie_walk8();void zombie_walk9();void zombie_walk10();void zombie_walk11();void zombie_walk12();void zombie_walk13();void zombie_walk14();void zombie_walk15();void zombie_walk16();void zombie_walk17();void zombie_walk18();void zombie_walk19();
void zombie_run2();void zombie_run3();void zombie_run4();void zombie_run5();void zombie_run6();void zombie_run7();void zombie_run8();void zombie_run9();void zombie_run10();void zombie_run11();void zombie_run12();void zombie_run13();void zombie_run14();void zombie_run15();void zombie_run16();void zombie_run17();void zombie_run18();
void zombie_atta2();void zombie_atta3();void zombie_atta4();void zombie_atta5();void zombie_atta6();void zombie_atta7();void zombie_atta8();void zombie_atta9();void zombie_atta10();void zombie_atta11();void zombie_atta12();void zombie_atta13();
void zombie_attb2();void zombie_attb3();void zombie_attb4();void zombie_attb5();void zombie_attb6();void zombie_attb7();void zombie_attb8();void zombie_attb9();void zombie_attb10();void zombie_attb11();void zombie_attb12();void zombie_attb13();void zombie_attb14();
void zombie_attc2();void zombie_attc3();void zombie_attc4();void zombie_attc5();void zombie_attc6();void zombie_attc7();void zombie_attc8();void zombie_attc9();void zombie_attc10();void zombie_attc11();void zombie_attc12();
void zombie_paina2();void zombie_paina3();void zombie_paina4();void zombie_paina5();void zombie_paina6();void zombie_paina7();void zombie_paina8();void zombie_paina9();void zombie_paina10();void zombie_paina11();void zombie_paina12();
void zombie_painb2();void zombie_painb3();void zombie_painb4();void zombie_painb5();void zombie_painb6();void zombie_painb7();void zombie_painb8();void zombie_painb9();void zombie_painb10();void zombie_painb11();void zombie_painb12();void zombie_painb13();void zombie_painb14();void zombie_painb15();void zombie_painb16();void zombie_painb17();void zombie_painb18();void zombie_painb19();void zombie_painb20();void zombie_painb21();void zombie_painb22();void zombie_painb23();void zombie_painb24();void zombie_painb25();void zombie_painb26();void zombie_painb27();void zombie_painb28();
void zombie_painc2();void zombie_painc3();void zombie_painc4();void zombie_painc5();void zombie_painc6();void zombie_painc7();void zombie_painc8();void zombie_painc9();void zombie_painc10();void zombie_painc11();void zombie_painc12();void zombie_painc13();void zombie_painc14();void zombie_painc15();void zombie_painc16();void zombie_painc17();void zombie_painc18();
void zombie_paind2();void zombie_paind3();void zombie_paind4();void zombie_paind5();void zombie_paind6();void zombie_paind7();void zombie_paind8();void zombie_paind9();void zombie_paind10();void zombie_paind11();void zombie_paind12();void zombie_paind13();
void zombie_paine2();void zombie_paine3();void zombie_paine4();void zombie_paine5();void zombie_paine6();void zombie_paine7();void zombie_paine8();void zombie_paine9();void zombie_paine10();void zombie_paine11();void zombie_paine12();void zombie_paine13();void zombie_paine14();void zombie_paine15();void zombie_paine16();void zombie_paine17();void zombie_paine18();void zombie_paine19();void zombie_paine20();void zombie_paine21();void zombie_paine22();void zombie_paine23();void zombie_paine24();void zombie_paine25();void zombie_paine26();void zombie_paine27();void zombie_paine28();void zombie_paine29();void zombie_paine30();
void _demon1_stand2();void _demon1_stand3();void _demon1_stand4();void _demon1_stand5();void _demon1_stand6();void _demon1_stand7();void _demon1_stand8();void _demon1_stand9();void _demon1_stand10();void _demon1_stand11();void _demon1_stand12();void _demon1_stand13();
void _demon1_walk2();void _demon1_walk3();void _demon1_walk4();void _demon1_walk5();void _demon1_walk6();void _demon1_walk7();void _demon1_walk8();
void _demon1_run2();void _demon1_run3();void _demon1_run4();void _demon1_run5();void _demon1_run6();
void _demon1_jump2();void _demon1_jump3();void _demon1_jump4();void _demon1_jump5();void _demon1_jump6();void _demon1_jump7();void _demon1_jump8();void _demon1_jump9();void _demon1_jump10();void _demon1_jump11();void _demon1_jump12();
void _demon1_atta2();void _demon1_atta3();void _demon1_atta4();void _demon1_atta5();void _demon1_atta6();void _demon1_atta7();void _demon1_atta8();void _demon1_atta9();void _demon1_atta10();void _demon1_atta11();void _demon1_atta12();void _demon1_atta13();void _demon1_atta14();void _demon1_atta15();
void _demon1_pain2();void _demon1_pain3();void _demon1_pain4();void _demon1_pain5();void _demon1_pain6();
void _demon1_die2();void _demon1_die3();void _demon1_die4();void _demon1_die5();void _demon1_die6();void _demon1_die7();void _demon1_die8();void _demon1_die9();
void boss_rise2();void boss_rise3();void boss_rise4();void boss_rise5();void boss_rise6();void boss_rise7();void boss_rise8();void boss_rise9();void boss_rise10();void boss_rise11();void boss_rise12();void boss_rise13();void boss_rise14();void boss_rise15();void boss_rise16();void boss_rise17();
void boss_idle2();void boss_idle3();void boss_idle4();void boss_idle5();void boss_idle6();void boss_idle7();void boss_idle8();void boss_idle9();void boss_idle10();void boss_idle11();void boss_idle12();void boss_idle13();void boss_idle14();void boss_idle15();void boss_idle16();void boss_idle17();void boss_idle18();void boss_idle19();void boss_idle20();void boss_idle21();void boss_idle22();void boss_idle23();void boss_idle24();void boss_idle25();void boss_idle26();void boss_idle27();void boss_idle28();void boss_idle29();void boss_idle30();void boss_idle31();
void boss_missile1();void boss_missile2();void boss_missile3();void boss_missile4();void boss_missile5();void boss_missile6();void boss_missile7();void boss_missile8();void boss_missile9();void boss_missile10();void boss_missile11();void boss_missile12();void boss_missile13();void boss_missile14();void boss_missile15();void boss_missile16();void boss_missile17();void boss_missile18();void boss_missile19();void boss_missile20();void boss_missile21();void boss_missile22();void boss_missile23();
void boss_shocka2();void boss_shocka3();void boss_shocka4();void boss_shocka5();void boss_shocka6();void boss_shocka7();void boss_shocka8();void boss_shocka9();void boss_shocka10();
void boss_shockb2();void boss_shockb3();void boss_shockb4();void boss_shockb5();void boss_shockb6();void boss_shockb7();void boss_shockb8();void boss_shockb9();void boss_shockb10();
void boss_shockc2();void boss_shockc3();void boss_shockc4();void boss_shockc5();void boss_shockc6();void boss_shockc7();void boss_shockc8();void boss_shockc9();void boss_shockc10();
void boss_death1();void boss_death2();void boss_death3();void boss_death4();void boss_death5();void boss_death6();void boss_death7();void boss_death8();void boss_death9();void boss_death10();
void ogre_stand2();void ogre_stand3();void ogre_stand4();void ogre_stand5();void ogre_stand6();void ogre_stand7();void ogre_stand8();void ogre_stand9();
void ogre_walk2();void ogre_walk3();void ogre_walk4();void ogre_walk5();void ogre_walk6();void ogre_walk7();void ogre_walk8();void ogre_walk9();void ogre_walk10();void ogre_walk11();void ogre_walk12();void ogre_walk13();void ogre_walk14();void ogre_walk15();void ogre_walk16();
void ogre_run2();void ogre_run3();void ogre_run4();void ogre_run5();void ogre_run6();void ogre_run7();void ogre_run8();
void ogre_swing2();void ogre_swing3();void ogre_swing4();void ogre_swing5();void ogre_swing6();void ogre_swing7();void ogre_swing8();void ogre_swing9();void ogre_swing10();void ogre_swing11();void ogre_swing12();void ogre_swing13();void ogre_swing14();
void ogre_smash2();void ogre_smash3();void ogre_smash4();void ogre_smash5();void ogre_smash6();void ogre_smash7();void ogre_smash8();void ogre_smash9();void ogre_smash10();void ogre_smash11();void ogre_smash12();void ogre_smash13();void ogre_smash14();
void ogre_nail2();void ogre_nail3();void ogre_nail4();void ogre_nail5();void ogre_nail6();void ogre_nail7();
void ogre_pain2();void ogre_pain3();void ogre_pain4();void ogre_pain5();
void ogre_painb2();void ogre_painb3();
void ogre_painc2();void ogre_painc3();void ogre_painc4();void ogre_painc5();void ogre_painc6();
void ogre_paind2();void ogre_paind3();void ogre_paind4();void ogre_paind5();void ogre_paind6();void ogre_paind7();void ogre_paind8();void ogre_paind9();void ogre_paind10();void ogre_paind11();void ogre_paind12();void ogre_paind13();void ogre_paind14();void ogre_paind15();void ogre_paind16();
void ogre_paine2();void ogre_paine3();void ogre_paine4();void ogre_paine5();void ogre_paine6();void ogre_paine7();void ogre_paine8();void ogre_paine9();void ogre_paine10();void ogre_paine11();void ogre_paine12();void ogre_paine13();void ogre_paine14();void ogre_paine15();
void ogre_die2();void ogre_die3();void ogre_die4();void ogre_die5();void ogre_die6();void ogre_die7();void ogre_die8();void ogre_die9();void ogre_die10();void ogre_die11();void ogre_die12();void ogre_die13();void ogre_die14();
void ogre_bdie2();void ogre_bdie3();void ogre_bdie4();void ogre_bdie5();void ogre_bdie6();void ogre_bdie7();void ogre_bdie8();void ogre_bdie9();void ogre_bdie10();
void knight_stand2();void knight_stand3();void knight_stand4();void knight_stand5();void knight_stand6();void knight_stand7();void knight_stand8();void knight_stand9();
void knight_walk2();void knight_walk3();void knight_walk4();void knight_walk5();void knight_walk6();void knight_walk7();void knight_walk8();void knight_walk9();void knight_walk10();void knight_walk11();void knight_walk12();void knight_walk13();void knight_walk14();
void knight_run2();void knight_run3();void knight_run4();void knight_run5();void knight_run6();void knight_run7();void knight_run8();
void knight_runatk2();void knight_runatk3();void knight_runatk4();void knight_runatk5();void knight_runatk6();void knight_runatk7();void knight_runatk8();void knight_runatk9();void knight_runatk10();void knight_runatk11();
void knight_atk2();void knight_atk3();void knight_atk4();void knight_atk5();void knight_atk6();void knight_atk7();void knight_atk8();void knight_atk9();void knight_atk10();
void knight_pain2();void knight_pain3();
void knight_painb2();void knight_painb3();void knight_painb4();void knight_painb5();void knight_painb6();void knight_painb7();void knight_painb8();void knight_painb9();void knight_painb10();void knight_painb11();
void knight_bow2();void knight_bow3();void knight_bow4();void knight_bow5();void knight_bow6();void knight_bow7();void knight_bow8();void knight_bow9();void knight_bow10();
void knight_die2();void knight_die3();void knight_die4();void knight_die5();void knight_die6();void knight_die7();void knight_die8();void knight_die9();void knight_die10();
void knight_dieb2();void knight_dieb3();void knight_dieb4();void knight_dieb5();void knight_dieb6();void knight_dieb7();void knight_dieb8();void knight_dieb9();void knight_dieb10();void knight_dieb11();
void _wiz_stand2();void _wiz_stand3();void _wiz_stand4();void _wiz_stand5();void _wiz_stand6();void _wiz_stand7();void _wiz_stand8();
void _wiz_walk2();void _wiz_walk3();void _wiz_walk4();void _wiz_walk5();void _wiz_walk6();void _wiz_walk7();void _wiz_walk8();
void _wiz_side2();void _wiz_side3();void _wiz_side4();void _wiz_side5();void _wiz_side6();void _wiz_side7();void _wiz_side8();
void _wiz_run2();void _wiz_run3();void _wiz_run4();void _wiz_run5();void _wiz_run6();void _wiz_run7();void _wiz_run8();void _wiz_run9();void _wiz_run10();void _wiz_run11();void _wiz_run12();void _wiz_run13();void _wiz_run14();
void _wiz_fast2();void _wiz_fast3();void _wiz_fast4();void _wiz_fast5();void _wiz_fast6();void _wiz_fast7();void _wiz_fast8();void _wiz_fast9();void _wiz_fast10();
void _wiz_pain2();void _wiz_pain3();void _wiz_pain4();
void _wiz_death2();void _wiz_death3();void _wiz_death4();void _wiz_death5();void _wiz_death6();void _wiz_death7();void _wiz_death8();
void _sham_stand2();void _sham_stand3();void _sham_stand4();void _sham_stand5();void _sham_stand6();void _sham_stand7();void _sham_stand8();void _sham_stand9();void _sham_stand10();void _sham_stand11();void _sham_stand12();void _sham_stand13();void _sham_stand14();void _sham_stand15();void _sham_stand16();void _sham_stand17();
void _sham_walk2();void _sham_walk3();void _sham_walk4();void _sham_walk5();void _sham_walk6();void _sham_walk7();void _sham_walk8();void _sham_walk9();void _sham_walk10();void _sham_walk11();void _sham_walk12();
void _sham_run2();void _sham_run3();void _sham_run4();void _sham_run5();void _sham_run6();
void _sham_smash2();void _sham_smash3();void _sham_smash4();void _sham_smash5();void _sham_smash6();void _sham_smash7();void _sham_smash8();void _sham_smash9();void _sham_smash10();void _sham_smash11();void _sham_smash12();
void _sham_swingl2();void _sham_swingl3();void _sham_swingl4();void _sham_swingl5();void _sham_swingl6();void _sham_swingl7();void _sham_swingl8();void _sham_swingl9();
void _sham_swingr2();void _sham_swingr3();void _sham_swingr4();void _sham_swingr5();void _sham_swingr6();void _sham_swingr7();void _sham_swingr8();void _sham_swingr9();
void _sham_throwl2();void _sham_throwl3();void _sham_throwl4();void _sham_throwl5();void _sham_throwl6();void _sham_throwl7();void _sham_throwl8();void _sham_throwl9();
void _sham_throwr2();void _sham_throwr3();void _sham_throwr4();void _sham_throwr5();void _sham_throwr6();void _sham_throwr7();void _sham_throwr8();void _sham_throwr9();
void _sham_magic2();void _sham_magic3();void _sham_magic4();void _sham_magic5();void _sham_magic6();void _sham_magic9();void _sham_magic10();void _sham_magic11();void _sham_magic12();
void _sham_pain2();void _sham_pain3();void _sham_pain4();void _sham_pain5();void _sham_pain6();
void _sham_death2();void _sham_death3();void _sham_death4();void _sham_death5();void _sham_death6();void _sham_death7();void _sham_death8();void _sham_death9();void _sham_death10();void _sham_death11();
void enf_stand2();void enf_stand3();void enf_stand4();void enf_stand5();void enf_stand6();void enf_stand7();
void enf_walk2();void enf_walk3();void enf_walk4();void enf_walk5();void enf_walk6();void enf_walk7();void enf_walk8();void enf_walk9();void enf_walk10();void enf_walk11();void enf_walk12();void enf_walk13();void enf_walk14();void enf_walk15();void enf_walk16();
void enf_run2();void enf_run3();void enf_run4();void enf_run5();void enf_run6();void enf_run7();void enf_run8();
void enf_atk2();void enf_atk3();void enf_atk4();void enf_atk5();void enf_atk6();void enf_atk7();void enf_atk8();void enf_atk9();void enf_atk10();void enf_atk11();void enf_atk12();void enf_atk13();void enf_atk14();
void enf_paina2();void enf_paina3();void enf_paina4();
void enf_painb2();void enf_painb3();void enf_painb4();void enf_painb5();
void enf_painc2();void enf_painc3();void enf_painc4();void enf_painc5();void enf_painc6();void enf_painc7();void enf_painc8();
void enf_paind2();void enf_paind3();void enf_paind4();void enf_paind5();void enf_paind6();void enf_paind7();void enf_paind8();void enf_paind9();void enf_paind10();void enf_paind11();void enf_paind12();void enf_paind13();void enf_paind14();void enf_paind15();void enf_paind16();void enf_paind17();void enf_paind18();void enf_paind19();
void enf_die2();void enf_die3();void enf_die4();void enf_die5();void enf_die6();void enf_die7();void enf_die8();void enf_die9();void enf_die10();void enf_die11();void enf_die12();void enf_die13();void enf_die14();
void enf_fdie2();void enf_fdie3();void enf_fdie4();void enf_fdie5();void enf_fdie6();void enf_fdie7();void enf_fdie8();void enf_fdie9();void enf_fdie10();void enf_fdie11();
void f_stand2();void f_stand3();void f_stand4();void f_stand5();void f_stand6();void f_stand7();void f_stand8();void f_stand9();void f_stand10();void f_stand11();void f_stand12();void f_stand13();void f_stand14();void f_stand15();void f_stand16();void f_stand17();void f_stand18();
void f_walk2();void f_walk3();void f_walk4();void f_walk5();void f_walk6();void f_walk7();void f_walk8();void f_walk9();void f_walk10();void f_walk11();void f_walk12();void f_walk13();void f_walk14();void f_walk15();void f_walk16();void f_walk17();void f_walk18();
void f_run2();void f_run3();void f_run4();void f_run5();void f_run6();void f_run7();void f_run8();void f_run9();
void f_attack2();void f_attack3();void f_attack4();void f_attack5();void f_attack6();void f_attack7();void f_attack8();void f_attack9();void f_attack10();void f_attack11();void f_attack12();void f_attack13();void f_attack14();void f_attack15();void f_attack16();void f_attack17();void f_attack18();
void f_death2();void f_death3();void f_death4();void f_death5();void f_death6();void f_death7();void f_death8();void f_death9();void f_death10();void f_death11();void f_death12();void f_death13();void f_death14();void f_death15();void f_death16();void f_death17();void f_death18();void f_death19();void f_death20();void f_death21();
void f_pain2();void f_pain3();void f_pain4();void f_pain5();void f_pain6();void f_pain7();void f_pain8();void f_pain9();
void tbaby_walk2();void tbaby_walk3();void tbaby_walk4();void tbaby_walk5();void tbaby_walk6();void tbaby_walk7();void tbaby_walk8();void tbaby_walk9();void tbaby_walk10();void tbaby_walk11();void tbaby_walk12();void tbaby_walk13();void tbaby_walk14();void tbaby_walk15();void tbaby_walk16();void tbaby_walk17();void tbaby_walk18();void tbaby_walk19();void tbaby_walk20();void tbaby_walk21();void tbaby_walk22();void tbaby_walk23();void tbaby_walk24();void tbaby_walk25();
void tbaby_run2();void tbaby_run3();void tbaby_run4();void tbaby_run5();void tbaby_run6();void tbaby_run7();void tbaby_run8();void tbaby_run9();void tbaby_run10();void tbaby_run11();void tbaby_run12();void tbaby_run13();void tbaby_run14();void tbaby_run15();void tbaby_run16();void tbaby_run17();void tbaby_run18();void tbaby_run19();void tbaby_run20();void tbaby_run21();void tbaby_run22();void tbaby_run23();void tbaby_run24();void tbaby_run25();
void tbaby_fly2();void tbaby_fly3();void tbaby_fly4();
void tbaby_jump2();void tbaby_jump3();void tbaby_jump4();void tbaby_jump5();void tbaby_jump6();
void tbaby_die2();
void shal_walk2();void shal_walk3();void shal_walk4();void shal_walk5();void shal_walk6();void shal_walk7();void shal_walk8();void shal_walk9();void shal_walk10();void shal_walk11();void shal_walk12();
void shal_run2();void shal_run3();void shal_run4();void shal_run5();void shal_run6();void shal_run7();void shal_run8();void shal_run9();void shal_run10();void shal_run11();void shal_run12();
void shal_attack2();void shal_attack3();void shal_attack4();void shal_attack5();void shal_attack6();void shal_attack7();void shal_attack8();void shal_attack9();void shal_attack10();void shal_attack11();
void shal_pain2();void shal_pain3();void shal_pain4();void shal_pain5();
void shal_death2();void shal_death3();void shal_death4();void shal_death5();void shal_death6();void shal_death7();
void hknight_stand2();void hknight_stand3();void hknight_stand4();void hknight_stand5();void hknight_stand6();void hknight_stand7();void hknight_stand8();void hknight_stand9();
void hknight_walk2();void hknight_walk3();void hknight_walk4();void hknight_walk5();void hknight_walk6();void hknight_walk7();void hknight_walk8();void hknight_walk9();void hknight_walk10();void hknight_walk11();void hknight_walk12();void hknight_walk13();void hknight_walk14();void hknight_walk15();void hknight_walk16();void hknight_walk17();void hknight_walk18();void hknight_walk19();void hknight_walk20();
void hknight_run2();void hknight_run3();void hknight_run4();void hknight_run5();void hknight_run6();void hknight_run7();void hknight_run8();
void hknight_pain2();void hknight_pain3();void hknight_pain4();void hknight_pain5();
void hknight_die2();void hknight_die3();void hknight_die4();void hknight_die5();void hknight_die6();void hknight_die7();void hknight_die8();void hknight_die9();void hknight_die10();void hknight_die11();void hknight_die12();
void hknight_dieb2();void hknight_dieb3();void hknight_dieb4();void hknight_dieb5();void hknight_dieb6();void hknight_dieb7();void hknight_dieb8();void hknight_dieb9();
void hknight_magica2();void hknight_magica3();void hknight_magica4();void hknight_magica5();void hknight_magica6();void hknight_magica7();void hknight_magica8();void hknight_magica9();void hknight_magica10();void hknight_magica11();void hknight_magica12();void hknight_magica13();void hknight_magica14();
void hknight_magicb2();void hknight_magicb3();void hknight_magicb4();void hknight_magicb5();void hknight_magicb6();void hknight_magicb7();void hknight_magicb8();void hknight_magicb9();void hknight_magicb10();void hknight_magicb11();void hknight_magicb12();void hknight_magicb13();
void hknight_magicc2();void hknight_magicc3();void hknight_magicc4();void hknight_magicc5();void hknight_magicc6();void hknight_magicc7();void hknight_magicc8();void hknight_magicc9();void hknight_magicc10();void hknight_magicc11();
void hknight_char_a2();void hknight_char_a3();void hknight_char_a4();void hknight_char_a5();void hknight_char_a6();void hknight_char_a7();void hknight_char_a8();void hknight_char_a9();void hknight_char_a10();void hknight_char_a11();void hknight_char_a12();void hknight_char_a13();void hknight_char_a14();void hknight_char_a15();void hknight_char_a16();
void hknight_char_b2();void hknight_char_b3();void hknight_char_b4();void hknight_char_b5();void hknight_char_b6();
void hknight_slice2();void hknight_slice3();void hknight_slice4();void hknight_slice5();void hknight_slice6();void hknight_slice7();void hknight_slice8();void hknight_slice9();void hknight_slice10();
void hknight_smash2();void hknight_smash3();void hknight_smash4();void hknight_smash5();void hknight_smash6();void hknight_smash7();void hknight_smash8();void hknight_smash9();void hknight_smash10();void hknight_smash11();
void hknight_watk2();void hknight_watk3();void hknight_watk4();void hknight_watk5();void hknight_watk6();void hknight_watk7();void hknight_watk8();void hknight_watk9();void hknight_watk10();void hknight_watk11();void hknight_watk12();void hknight_watk13();void hknight_watk14();void hknight_watk15();void hknight_watk16();void hknight_watk17();void hknight_watk18();void hknight_watk19();void hknight_watk20();void hknight_watk21();void hknight_watk22();
void old_idle2();void old_idle3();void old_idle4();void old_idle5();void old_idle6();void old_idle7();void old_idle8();void old_idle9();void old_idle10();void old_idle11();void old_idle12();void old_idle13();void old_idle14();void old_idle15();void old_idle16();void old_idle17();void old_idle18();void old_idle19();void old_idle20();void old_idle21();void old_idle22();void old_idle23();void old_idle24();void old_idle25();void old_idle26();void old_idle27();void old_idle28();void old_idle29();void old_idle30();void old_idle31();void old_idle32();void old_idle33();void old_idle34();void old_idle35();void old_idle36();void old_idle37();void old_idle38();void old_idle39();void old_idle40();void old_idle41();void old_idle42();void old_idle43();void old_idle44();void old_idle45();void old_idle46();
void old_thrash2();void old_thrash3();void old_thrash4();void old_thrash5();void old_thrash6();void old_thrash7();void old_thrash8();void old_thrash9();void old_thrash10();void old_thrash11();void old_thrash12();void old_thrash13();void old_thrash14();void old_thrash15();void old_thrash16();void old_thrash17();void old_thrash18();void old_thrash19();void old_thrash20();
void finale_2();void finale_3();void finale_4();
#endif // PR_COOP_MODE_ENHANCED
// PZ: END - Stupid forward declarations for frame functions.
