#ifndef FISH_H
#define FISH_H

namespace Progs {

void coop_swimmonster_start();
void f_stand1();
void f_stand2();
void f_stand3();
void f_stand4();
void f_stand5();
void f_stand6();
void f_stand7();
void f_stand8();
void f_stand9();
void f_stand10();
void f_stand11();
void f_stand12();
void f_stand13();
void f_stand14();
void f_stand15();
void f_stand16();
void f_stand17();
void f_stand18();
void f_walk1();
void f_walk2();
void f_walk3();
void f_walk4();
void f_walk5();
void f_walk6();
void f_walk7();
void f_walk8();
void f_walk9();
void f_walk10();
void f_walk11();
void f_walk12();
void f_walk13();
void f_walk14();
void f_walk15();
void f_walk16();
void f_walk17();
void f_walk18();
void f_run1();
void f_run2();
void f_run3();
void f_run4();
void f_run5();
void f_run6();
void f_run7();
void f_run8();
void f_run9();
void _fish_melee();
void f_attack1();
void f_attack2();
void f_attack3();
void f_attack4();
void f_attack5();
void f_attack6();
void f_attack7();
void f_attack8();
void f_attack9();
void f_attack10();
void f_attack11();
void f_attack12();
void f_attack13();
void f_attack14();
void f_attack15();
void f_attack16();
void f_attack17();
void f_attack18();
void f_death1();
void f_death2();
void f_death3();
void f_death4();
void f_death5();
void f_death6();
void f_death7();
void f_death8();
void f_death9();
void f_death10();
void f_death11();
void f_death12();
void f_death13();
void f_death14();
void f_death15();
void f_death16();
void f_death17();
void f_death18();
void f_death19();
void f_death20();
void f_death21();
void f_pain1();
void f_pain2();
void f_pain3();
void f_pain4();
void f_pain5();
void f_pain6();
void f_pain7();
void f_pain8();
void f_pain9();
void _fish_pain(entity attacker, float damage);
float _fish_noticeenemy();
void monster_fish();

} // END namespace Progs

#endif // END FISH_H

